apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: smart-mon
  namespace: monitoring
spec:
  updateStrategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: smart-mon
      app: smart-mon
  template:
    metadata:
      labels:
        app.kubernetes.io/name: smart-mon
        app: smart-mon
      annotations:
        prometheus.io/path: "/metrics"
        prometheus.io/scrape: 'true'
        prometheus.io/port: '9898'
    spec:
      containers:
        - name: smart-mon-pod
          image: jbalcas/smart-mon:latest
          securityContext:
            privileged: true
            capabilities:
              add:
                - CAP_SYS_ADMIN
          env:
          - name: HTTP_PORT
            value: "9898"
          - name: WORK_DIR
            value: "/opt/"
          - name: SLEEP_TIMER
            value: "10"
          - name: MY_HOSTNAME
            valueFrom:
              fieldRef:
                fieldPath: spec.nodeName
          resources:
            limits:
              memory: 200Mi
              cpu: 200m
            requests:
              memory: 200Mi
              cpu: 200m
          ports:
            - containerPort: 9898
          volumeMounts:
            - mountPath: /dev/
              name: host-dev
          command: ["sh", "-c", "/kube-smart-mon -path /opt"]
      volumes:
        - name: host-dev
          hostPath:
            path: /dev
      tolerations:
        - effect: NoSchedule
          operator: Exists
