{
 "title": "S.M.A.R.T disk monitoring for Prometheus Dashboard",
 "description": "Smartmon Texfile node_exporter Dashboard",
 "tags": [
  "prometheus",
  "node_exporter",
  "smartmon"
 ],
 "time": { "from": "now-7d", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "hostname",
    "query": {
     "query": "label_values(smartmon_smartctl_version, hostname)"
    }
   },
   {
    "name": "disk",
    "query": {
     "query": "label_values(smartmon_device_info, disk)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Active devices",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sum(smartmon_device_active)" }
   ]
  },
  {
   "title": "Temperature_Graph",
   "type": "graph",
   "gridPos": { "h": 8, "w": 21, "x": 3, "y": 0 },
   "yaxes": [
    { "format": "celsius" }
   ],
   "targets": [
    {
     "expr": "avg(smartmon_temperature_celsius_raw_value{ hostname=~\"$hostname\", disk=~\"$disk\" }) by (hostname, disk)",
     "legendFormat": "{{disk}} {{hostname}}"
    }
   ]
  },
  {
   "title": "Device_Info",
   "type": "table-old",
   "gridPos": { "h": 15, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "smartmon_device_info{hostname=~\"$hostname\"}"
    }
   ]
  },
  {
   "title": "$hostname",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 },
   "repeat": "hostname",
   "collapsed": true,
   "panels": [
    {
     "type": "text",
     "gridPos": { "h": 2, "w": 24, "x": 0, "y": 24 },
     "options": {
      "content": "<p></p>\n<p style=\"text-align: center;font-size: x-large;face:arial;\">__________ NVME __________</p>"
     },
     "targets": [
      {}
     ]
    },
    {
     "title": "Device Active",
     "type": "gauge",
     "gridPos": { "h": 5, "w": 12, "x": 0, "y": 26 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "smartmon_device_active{disk=~\"$disk\", hostname=~\"$hostname\", type=~\"nvme\"}",
       "legendFormat": " {{disk}}"
      }
     ]
    },
    {
     "title": "SMART Healthy",
     "type": "gauge",
     "gridPos": { "h": 5, "w": 12, "x": 12, "y": 26 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "smartmon_device_smart_healthy{disk=~\"$disk\", hostname=~\"$hostname\", type=~\"nvme\"}",
       "legendFormat": " {{disk}}"
      }
     ]
    },
    {
     "title": "Power On Hours",
     "type": "gauge",
     "gridPos": { "h": 5, "w": 12, "x": 0, "y": 31 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "smartmon_power_on_hours_raw_value{disk=~\"$disk\", hostname=~\"$hostname\", type=~\"nvme\"}",
       "legendFormat": " {{disk}}"
      }
     ]
    },
    {
     "title": "Temperature",
     "type": "gauge",
     "gridPos": { "h": 5, "w": 12, "x": 12, "y": 31 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "smartmon_temperature_celsius_raw_value{disk=~\"$disk\", hostname=~\"$hostname\", type=~\"nvme\"}",
       "legendFormat": " {{disk}}"
      }
     ]
    },
    {
     "title": "Percentage Used",
     "type": "gauge",
     "gridPos": { "h": 5, "w": 12, "x": 0, "y": 36 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "smartmon_percentage_used_raw_value{disk=~\"$disk\", hostname=~\"$hostname\", type=~\"nvme\"}",
       "legendFormat": " {{disk}}"
      }
     ]
    },
    {
     "title": "Percentage Used",
     "type": "gauge",
     "gridPos": { "h": 5, "w": 12, "x": 12, "y": 36 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "smartmon_unsafe_shutdowns_count_raw_value{disk=~\"$disk\", hostname=~\"$hostname\", type=~\"nvme\"}",
       "legendFormat": " {{disk}}"
      }
     ]
    },
    {
     "type": "text",
     "gridPos": { "h": 2, "w": 24, "x": 0, "y": 41 },
     "options": {
      "content": "<p></p>\n<p style=\"text-align: center;font-size: x-large;face:arial;\">__________ SAT __________</p>"
     },
     "targets": [
      {}
     ]
    },
    {
     "title": "Device Active",
     "type": "gauge",
     "gridPos": { "h": 5, "w": 12, "x": 0, "y": 43 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "smartmon_device_active{disk=~\"$disk\", hostname=~\"$hostname\", type=~\"sat\"}",
       "legendFormat": " {{disk}}"
      }
     ]
    },
    {
     "title": "SMART Healthy",
     "type": "gauge",
     "gridPos": { "h": 5, "w": 12, "x": 12, "y": 43 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "smartmon_device_smart_healthy{disk=~\"$disk\", hostname=~\"$hostname\", type=~\"sat\"}",
       "legendFormat": " {{disk}}"
      }
     ]
    },
    {
     "title": "Power On Hours",
     "type": "gauge",
     "gridPos": { "h": 5, "w": 12, "x": 0, "y": 48 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "smartmon_power_on_hours_raw_value{disk=~\"$disk\", hostname=~\"$hostname\", type=~\"sat\"}",
       "legendFormat": " {{disk}}"
      }
     ]
    },
    {
     "title": "Temperature",
     "type": "gauge",
     "gridPos": { "h": 5, "w": 12, "x": 12, "y": 48 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "smartmon_temperature_celsius_raw_value{disk=~\"$disk\", hostname=~\"$hostname\", type=~\"sat\"}",
       "legendFormat": " {{disk}}"
      }
     ]
    },
    {
     "title": "Read/Seek/CRC/Uncorrectable Error Count",
     "type": "graph",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 53 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "avg(smartmon_raw_read_error_rate_raw_value{ hostname=~\"$hostname\", disk=~\"$disk\", type=~\"sat\" }) by (hostname, disk)",
       "legendFormat": "Read Errors {{disk}} {{hostname}}"
      },
      {
       "expr": "avg(smartmon_seek_error_rate_raw_value{ hostname=~\"$hostname\", disk=~\"$disk\", type=~\"sat\" }) by (hostname, disk)",
       "legendFormat": "Seek Errors {{disk}} {{hostname}}"
      },
      {
       "expr": "avg(smartmon_udma_crc_error_count_raw_value{ hostname=~\"$hostname\", disk=~\"$disk\", type=~\"sat\" }) by (hostname, disk)",
       "legendFormat": "UDMA CRC Errors {{disk}} {{hostname}}"
      },
      {
       "expr": "avg(smartmon_offline_uncorrectable_raw_value{ hostname=~\"$hostname\", disk=~\"$disk\", type=~\"sat\" }) by (hostname, disk)",
       "legendFormat": "Offline Uncorrectable Errors {{disk}} {{hostname}}"
      }
     ]
    },
    {
     "type": "text",
     "gridPos": { "h": 2, "w": 24, "x": 0, "y": 61 },
     "options": {
      "content": "<p></p>\n<p style=\"text-align: center;font-size: x-large;face:arial;\">__________ SCSI __________</p>"
     },
     "targets": [
      {}
     ]
    },
    {
     "title": "Device Active",
     "type": "gauge",
     "gridPos": { "h": 5, "w": 12, "x": 0, "y": 63 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "smartmon_device_active{disk=~\"$disk\", hostname=~\"$hostname\", type=~\"scsi\"}",
       "legendFormat": " {{disk}}"
      }
     ]
    },
    {
     "title": "SMART Healthy",
     "type": "gauge",
     "gridPos": { "h": 5, "w": 12, "x": 12, "y": 63 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "smartmon_device_smart_healthy{disk=~\"$disk\", hostname=~\"$hostname\", type=~\"scsi\"}",
       "legendFormat": " {{disk}}"
      }
     ]
    },
    {
     "title": "Power Cycle Count",
     "type": "gauge",
     "gridPos": { "h": 5, "w": 12, "x": 0, "y": 68 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "smartmon_power_cycle_count_raw_value{disk=~\"$disk\", hostname=~\"$hostname\", type=~\"scsi\"}",
       "legendFormat": " {{disk}}"
      }
     ]
    },
    {
     "title": "Temperature",
     "type": "gauge",
     "gridPos": { "h": 5, "w": 12, "x": 12, "y": 68 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "smartmon_temperature_celsius_raw_value{disk=~\"$disk\", hostname=~\"$hostname\", type=~\"scsi\"}",
       "legendFormat": " {{disk}}"
      }
     ]
    },
    {
     "type": "text",
     "gridPos": { "h": 2, "w": 24, "x": 0, "y": 73 },
     "options": {
      "content": "<p></p>\n<p style=\"text-align: center;font-size: x-large;face:arial;\">__________ Megaraid* __________</p>"
     },
     "targets": [
      {}
     ]
    },
    {
     "title": "Device Active",
     "type": "gauge",
     "gridPos": { "h": 5, "w": 12, "x": 0, "y": 75 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "smartmon_device_active{disk=~\"$disk\", hostname=~\"$hostname\", type=~\"megaraid.*\"}",
       "legendFormat": "{{type}}"
      }
     ]
    },
    {
     "title": "SMART Healthy",
     "type": "gauge",
     "gridPos": { "h": 5, "w": 12, "x": 12, "y": 75 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "smartmon_device_smart_healthy{disk=~\"$disk\", hostname=~\"$hostname\", type=~\"megaraid.*\"}",
       "legendFormat": "{{type}}"
      }
     ]
    },
    {
     "title": "Power Cycle Count",
     "type": "gauge",
     "gridPos": { "h": 5, "w": 12, "x": 0, "y": 80 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "smartmon_power_cycle_count_raw_value{disk=~\"$disk\", hostname=~\"$hostname\", type=~\"megaraid.*\"}",
       "legendFormat": "{{type}}"
      }
     ]
    },
    {
     "title": "Temperature",
     "type": "gauge",
     "gridPos": { "h": 5, "w": 12, "x": 12, "y": 80 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "smartmon_temperature_celsius_raw_value{disk=~\"$disk\", hostname=~\"$hostname\", type=~\"megaraid.*\"}",
       "legendFormat": "{{type}}"
      }
     ]
    }
   ]
  }
 ]
}